### ISSUE TITLE
Actualizar vruntime

### ISSUE THREAD

**Issue by gustavoaca1997** [CI4821-Sep-Dic-2019/scheduler#15]
```java
vruntime += t * priority;
```

**Comment by rubmary** [comment]
Agregue la actualizacion usando esa formula cuando el ioBurst es false.
No estoy segura de si eso es suficiente, asi que dejare este issue abierto hasta que @gustavoaca1997 lo verifique
Solo eran 3 lineas de codigo asi que no hice pull request

**Comment by gustavoaca1997** [comment]
esto ya está listo cierto? @rubmary
