### ISSUE TITLE
Crear GUI

### ISSUE THREAD

**Issue by gustavoaca1997** [CI4821-Sep-Dic-2019/scheduler#6]
Creo que una opción común es usar Swing, sin embargo se pueden considerar más opciones. Tomar en cuenta que debe ser una interfaz muy sencilla y tonta.
Debe tener una manera de cargar o pegar un YAML con los parametros de entrada del simulador. Debe mostrar información en tiempo real de los hilos al estilo el comando `top` de UNIX, mostrando por cada proceso información como _PID, Nombre_del_proceso, %CPU_. Además se debe mostrar en tiempo real el número de tareas vivas, tareas corriendo, bloqueadas, etc. 

Si se les ocurren más cosas que mostrar, colocarlas en un comentario aquí.

**Comment by gustavoaca1997** [comment]
La idea del logger es usarlo para que redirija la salida a la interfaz

**Comment by rubmary** [comment]
La interfaz está creada \o/
Cerraré este issue porque abrí un par más con las cosas que hay que agregar o acomodar.
